version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd client
      - npm i -g npm@8.6.0
      - npm -v
      - npm install --silent --no-progress
      - npm run build
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'
  base-directory: 'client/build'