version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd server
      - npm install --silent --no-progress -g typescript
      - npm install --silent --no-progress
      - tsc
# Include only the files required for your application to run.
artifacts:
  files:
    - dist/**/*
    - package.json
    - package-lock.json
    - node_modules/**/*
  base-directory: 'server'