name: Generate terraform docs
on:
  - pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
        
    - name: Render terraform example complete docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: ./examples/complete
        output-file: README.md
        output-method: inject
        git-push: "true"

    - name: Render terraform example simple docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: ./examples/complete
        output-file: README.md
        output-method: inject
        git-push: "true"